mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    # To polls:
    # Always use include() - except for admin
    path("", include("polls.urls"), name="Polls"),
    # path(route, view, kwards, name)
]

polls/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.QuestionListView.as_view(), name="index"),
    path("<int:pk>/", views.QuestionDetailView.as_view(), name="details"),
    path("<int:pk>/results/", views.ResultsDetailView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    # Template views:
    path("about/", TemplateView.as_view(template_name="polls/about.html")),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    """Model definition for Question."""

    question_text = models.CharField(max_length=50)
    pub_date = models.DateTimeField(
        "date published", auto_now=False, auto_now_add=False
    )

    class Meta:
        """Meta definition for Question."""

        verbose_name = "Question"
        verbose_name_plural = "Questions"

    def __str__(self):
        """Unicode representation of Question."""
        return self.question_text

    # METHODS
    # ADMIN
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        return (
            timezone.now()
            >= self.pub_date
            >= (timezone.now() - datetime.timedelta(days=1))
        )


class Choice(models.Model):
    """Model definition for Choice."""

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    class Meta:
        """Meta definition for Choice."""

        verbose_name = "Choice"
        verbose_name_plural = "Choices"

    def __str__(self):
        """Unicode representation of Choice."""
        return self.choice_text

polls/views.py
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django import forms

from .models import Question, Choice


class QuestionListView(ListView):
    template_name = "polls/index.html"
    context_object_name = "questions"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by(
            "-pub_date"
        )[:5]


class QuestionDetailView(DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsDetailView(DetailView):
    model = Question
    template_name = "polls/results.html"


# LOGIC
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "polls/detail.html",
            {"question": question, "error_message": "NOOOOOO"},
        )
    selected_choice.votes += 1
    selected_choice.save()
    return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

polls/templates/polls/about.html
<h1>ABOUT!</h1>
{{test}}

polls/templates/polls/create_question.html
<form method="post">
    {% csrf_token %} {{ form.as_p }}
    <input type="submit" value="Save">
</form>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{ question.question_text }}</h1>
        </legend>
        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>{% endif %} {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br> {% endfor %}
    </fieldset><input type="submit" value="Vote"></form>

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>

<body>
    {{ test }} {% if questions %}
    <ul>
        {% for q in questions %}
        <li>
            <a href="{% url 'polls:details' q.id %}">{{q.question_text}}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available</p>
    {% endif %}
    <h1>IMAGE</h1>
    <img src="{% static 'polls/images/image.png'%}" alt="">
</body>

</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:details' question.id %}">Vote again?</a>